spring.application.name=AI_api

#mongodb
spring.data.mongodb.uri = mongodb://root:Luxshare%40ai@10.180.248.140:27017/admin

#redis
spring.redis.host=10.180.248.140
spring.redis.port=6379
spring.redis.password=AI-Redis@Luxshare-prod
spring.redis.database=0

#models
ai.models[0] = default
ai.models[1] = qwen3-reasoning

#AI-url
ai.categories.HR = http://10.180.116.2:1234/query
ai.categories.IT = http://10.180.116.2:9005/query
ai.categories.Law = http://10.180.116.2:9010/api/chat
ai.categories.summary = http://10.180.116.2:9005/summarize
ai.categories.translate = http://10.180.116.2:9005/translate
ai.categories.chat = http://10.180.116.2:9005/chat
ai.categories.unifiedChat = http://10.180.116.2:9005/unified_chat
ai.categories.imgRecognition = http://10.180.116.2:20000/api/v1/image-compare/chat/stream
ai.categories.imgRecognitionPlus = http://10.180.116.2:20000/api/v1/image-compare/workflow/stream
ai.categories.excelChat = http://10.180.116.2:20000/api/v1/excel/chat/stream
ai.categories.agentSetting = http://10.180.116.2:9005/prompt_fill
ai.categories.similarity = http://10.180.116.2:9005/similarity
ai.categories.glossary = http://10.180.116.2:5433/glossary

#libreOffice
libreoffice_tasks = http://10.180.248.143:8081/converter/processTasks
libreoffice_convert = http://10.180.248.143:8081/convert
libreoffice_ready = http://10.180.248.143:8081/convert/ready
libreoffice_departmentFile = http://10.180.248.143:8081/converter/processDepartmentFiles
libreoffice_publicConvert = http://10.180.248.143:8081/converter/processPublicKnowledgeInfos
libreoffice_FileUploads = http://10.180.248.143:8081/converter/processFileUploads

#minio
minio.endpoint = https://minio-urp.luxshare-tech.com/
minio.accessKey = qAsgj9U3D3OeficCGBYx
minio.secretKey = 2p0fdcTPt1M2gAApJESo0WosPyTCkpsKgAZupNLS
minio.bucketName = ai-files

minio-proxy = https://ai.luxshare-tech.com/minio-proxy/
local = http://10.180.248.140:9000/

resumeCallback = http://10.180.248.140:8080/Resume/resumeTaskComplete
uploadExcelTranslate = http://10.180.248.141:8080/minio/uploadExcelTranslate

ai-platform.pushUrls.HR= http://10.180.116.2:1234/file_processor
ai-platform.pushUrls.IT= http://10.180.116.2:9005/file_processor
ai-platform-push-interval-ms=600000
ai-platform.keys[0] = HR
ai-platform.keys[1] = IT
